---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mshayan/public_html/sentec.live/sentec
    - echo "Starting deployment to $DEPLOYPATH"
    - /bin/cp -r ./* $DEPLOYPATH
    - echo "Deployment completed successfully!"
